check_for_supported_tls:
  comment: 'done'
check_for_environment_variable_use_in_python:
  comment: 'done'
check_for_builtin_functions:
  comment: 'done'
check_for_data_compression_and_archiving:
  comment: 'done'
check_python_untrusted_xml_functions:
  comment: 'done'
check_for_file_and_directory_access:
  comment: 'done'
name_of_manual_check_2:
  comment: 'done'
