name: Triage Issues

on:
  issues:
    types: [opened]

jobs:
  call-workflow:
    uses: splunk-platform-apps/.github/.github/workflows/reusable-triage-issues.yml@main
    with:
      issue_number: ${{ github.event.issue.number }}
      issue_labels: "${{ join(github.event.issue.labels.*.name, ',') }}"
