name: Test Splunk TA Installs

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]
    paths:
      - package/**

# Allow only 1 concurrent execution
concurrency:
  group: ${{ '{{' }} github.workflow {{ '}}' }}-${{ '{{' }} github.ref {{ '}}' }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  call-workflow:
    uses: splunk-platform-apps/.github/.github/workflows/reusable-test-ta-install.yml@v1
    with:
      addon_name: SplunkCommunity_TA_UCCExample
