name: Quality Assessment

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]
    paths:
      - 'package/**'
      - '!package/app.manifest'
      - '!package/LICENSES/**'

# Allow only 1 concurrent execution
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow:
    if: github.repository != 'splunk-platform-apps/template-addon'
    uses: splunk-platform-apps/.github/.github/workflows/reusable-quality-assessment.yml@main
